Add module ADR
caikit/caikit pull request #155
Opened 2023-05-30 14:56 UTC by hickeyma

Partial #13

2023-05-30 21:07 UTC, gabe-l-hart requested changes
Thanks for putting this all in! This is much more thorough than the stub I'd started, so rather than giving you my half-formed version, I've just added a bunch of thoughts/suggestions here.

2023-06-06 09:55 UTC, hickeyma commented on docs/adrs/001-module.md
> +Currently, each module implements the following APIs, some of which can be considered core (implemented by all moduyles),
Fixed

2023-06-06 09:56 UTC, hickeyma commented on docs/adrs/001-module.md
> +`__init__` is the constructor for the module and should take only in-memory data structures, relevant to the block implementation.
Updated

2023-06-06 09:57 UTC, hickeyma commented on docs/adrs/001-module.md
> +Since python does not have constructor overloading, having a primitive, in-memory constructor allows us to implement multiple ways of instantiating blocks by using classmethods.
Updated

2023-06-06 10:01 UTC, hickeyma commented on docs/adrs/001-module.md
> +A module wraps one or more AI algorithms, and provides a crisply defined interface for obtaining predictions by providing one or more data model objects as input and returns exactly one data model ob
Updated

2023-06-06 10:03 UTC, hickeyma commented on docs/adrs/001-module.md
> +such as `.__init__()`, `.run()` and some which may not be present in all (like `.train()`). Additionally, modules come with some helper methods that are useful in analyzing block performance.
Is `run()` now optional or required?

2023-06-06 10:07 UTC, hickeyma commented on docs/adrs/001-module.md
> +So, `run` is very much like a `predict` method in other frameworks and we often use them in our verbiage interchangeably.
Updated

2023-06-06 10:08 UTC, hickeyma commented on docs/adrs/001-module.md
> +`train` is a python `@classmethod` that takes one or more [data stream]() instances as inputs containing training data and, potentially, other necessary arguments.
Not sure whether we want a reference to the data stream ADR or not here?

2023-06-06 10:09 UTC, hickeyma commented on docs/adrs/001-module.md
> +The `train` method creates a new instance of the module, in memory, that can later be saved to disk using `save()`.
Updated

2023-06-06 10:11 UTC, hickeyma commented on docs/adrs/001-module.md
> +So, `train` is similar to `fit` in some frameworks. Not all modules will have a `train` implemented.
Updated

2023-06-06 10:12 UTC, hickeyma commented on docs/adrs/001-module.md
> +
Added

2023-06-06 10:14 UTC, hickeyma commented
Thanks for the review and feedback @gabe-l-hart. Comments updated and some unresolved that require further feedback.

Ready for review again.

2023-06-07 14:25 UTC, gabe-l-hart commented on docs/adrs/001-module.md
> +`train` is a python `@classmethod` that takes one or more [data stream]() instances as inputs containing training data and, potentially, other necessary arguments.
Yeah, an ADR would be a good link here too. No strong preferences.

2023-06-07 14:25 UTC, gabe-l-hart commented
@hickeyma Responded to questions 🏓

2023-06-07 18:01 UTC, hickeyma commented on docs/adrs/001-module.md
> +such as `.__init__()`, `.run()` and some which may not be present in all (like `.train()`). Additionally, modules come with some helper methods that are useful in analyzing block performance.
Understand now. Updated to specify this.

2023-06-07 18:03 UTC, hickeyma commented on docs/adrs/001-module.md
> +This may feel a little overly prescriptive, but it allows us to keep things organized and also to have a generic server that can swap out different algorithms for a given module type.
Removing the sentences for now. We can add to this later when we have the task ADR.

2023-06-07 18:04 UTC, hickeyma commented on docs/adrs/001-module.md
> +`train` is a python `@classmethod` that takes one or more [data stream]() instances as inputs containing training data and, potentially, other necessary arguments.
I'll leave it with the empty reference for now and we can add the add when it is ready

2023-06-07 18:06 UTC, hickeyma commented on docs/adrs/001-module.md
> +Different algorithms of the same module type return the same type of output, but may take different kinds of inputs.
Removed for now, lets revisit when task add available.

2023-06-07 18:11 UTC, gabe-l-hart requested changes
One more typo NIT, and it looks like stream didn't get removed, even though you commented Done

2023-06-07 18:11 UTC, gabe-l-hart commented on docs/adrs/001-module.md
> +Currently, each module implements the following APIs, some of which can be considered core (implemented by all moduyles),
```suggestion
Currently, each module implements the following APIs, some of which can be considered core (implemented by all modules),
```

2023-06-07 18:26 UTC, closed without merging