Fix: Closures in DataStreams prevent pickling
caikit/caikit pull request #192
Opened 2023-06-07 21:10 UTC by kellyaa

This PR fixes #157 

Authored with copious input from @joerunde

2023-06-07 21:20 UTC, gabe-l-hart commented
@kellyaa To get DCO to pass, you'll need to:

```sh
git rebase origin/main --signoff
git push -f
```

2023-06-08 18:12 UTC, joerunde approved these changes
Looks great!

The only comments I have are more future looking:
- If we're trying to ensure that all of our `from_*` stream constructors are pickleable, should we add tests for every one? On the one hand it seems a bit overkill, on the other we do need this tested somewhere if it's critical to the ray pieces, but maybe we could ensure that's covered when we land the ray training bits.
- There are plenty of other places here where we use lambdas, like `map` and `filter`. Should we address those now as well? Or open an issue about it?
- This is probably worth a small comment in the DataStream class docstring about why we want to avoid lambdas if possible

2023-06-08 18:42 UTC, gabe-l-hart requested changes
NITs about proactive log formatting (sorry!) but otherwise it's good to go

2023-06-09 14:45 UTC, kellyaa commented on caikit/core/data_model/streams/data_stream.py
> +            log.debug2("Loading JSON array file: {}".format(filename))
Will put this in next commit.

2023-06-09 14:45 UTC, kellyaa commented on caikit/core/data_model/streams/data_stream.py
> +    def _from_iterable_generator(cls, data: typing.Iterable[T]):
Will put this in next commit

2023-06-09 16:22 UTC, gabe-l-hart requested changes
I think there are a couple of places where we need to go back to `.format` when explicitly creating error string

2023-06-09 16:22 UTC, gabe-l-hart commented on caikit/core/data_model/streams/data_stream.py
> +                    "csv filename %s does not exist or is not a regular file.", filename
Shoot, this actually _doesn't_ work. When instantiating an exception, using `.format` (or the old school `"foo %s" % "bar"` syntax) to explicitly do the formatting is what you want to do. It's only in arguments to logging functions that you want to use `,` to delay the interpolation

2023-06-09 18:57 UTC, gabe-l-hart approved these changes
Looks good!

2023-06-09 18:57 UTC, merged