update saver to take args
caikit/caikit pull request #431
Opened 2023-08-22 19:31 UTC by Ssukriti

**What this PR does / why we need it**:
Both watson_nlp and caikit_nlp pass args to save in certain modules. 

**Special notes for your reviewer**:
Blocking other efforts, kindly prioritize
 
**If applicable**:
- [ ] this PR contains documentation
- [ ] this PR contains unit tests
- [ ] this PR has been tested for backwards compatibility

2023-08-22 19:33 UTC, gabe-l-hart requested changes
Thanks Sukriti! Can you throw a unit test in somewhere to ensure that this works end-to-end so that we don't accidentally break this in the future?

2023-08-22 23:47 UTC, Ssukriti commented on tests/core/modules/test_module.py
> +def test_save_module(model_path):
just FYI, these are taken from watson_core

2023-08-23 13:38 UTC, gabe-l-hart requested changes
Thanks for adding all of these! Let's change the word `block` to `model` everywhere since we've officially removed the notion of a `block` in `caikit`. Otherwise it looks good to go

2023-08-23 13:38 UTC, gabe-l-hart commented on tests/core/modules/test_module.py
> +    dummy_block = caikit.core.load(model_path)
```suggestion
    dummy_model = caikit.core.load(model_path)
```

2023-08-23 13:38 UTC, gabe-l-hart commented on tests/core/modules/test_module.py
> +            dummy_block,
```suggestion
            dummy_model,
```

2023-08-23 13:38 UTC, gabe-l-hart commented on tests/core/modules/test_module.py
> +            module_saver.save_module(dummy_block, "dummy")
```suggestion
            module_saver.save_module(dummy_model, "dummy")
```

2023-08-23 13:38 UTC, gabe-l-hart commented on tests/core/modules/test_module.py
> +    dummy_block = caikit.core.load(model_path)
```suggestion
    dummy_model = caikit.core.load(model_path)
```

2023-08-23 13:38 UTC, gabe-l-hart commented on tests/core/modules/test_module.py
> +            module_saver.save_module(dummy_block, "dummy", keyword=True)
```suggestion
            module_saver.save_module(dummy_model, "dummy", keyword=True)
```

2023-08-23 13:38 UTC, gabe-l-hart commented on tests/core/modules/test_module.py
> +            saved_block = caikit.core.load(os.path.join(tempdir, "dummy"))
```suggestion
            saved_model = caikit.core.load(os.path.join(tempdir, "dummy"))
```

2023-08-23 13:38 UTC, gabe-l-hart commented on tests/core/modules/test_module.py
> +            assert saved_block.metadata["test_keyword"]
```suggestion
            assert saved_model.metadata["test_keyword"]
```

2023-08-23 13:38 UTC, gabe-l-hart commented on tests/core/modules/test_module.py
> +    """Test valid module list save with a list of syntax blocks."""
```suggestion
    """Test valid module list save with a list of models."""
```

2023-08-23 13:38 UTC, gabe-l-hart commented on tests/core/modules/test_module.py
> +    dummy_models_with_rel_path = {"dummy_path": dummy_block}
```suggestion
    dummy_models_with_rel_path = {"dummy_path": dummy_model}
```

2023-08-23 13:38 UTC, gabe-l-hart commented on tests/core/modules/test_module.py
> +            dummy_block,
```suggestion
            dummy_model,
```

2023-08-23 13:38 UTC, gabe-l-hart commented on tests/core/modules/test_module.py
> +    """Check that additional keywords passed to save_module_list are processed by the block"""
```suggestion
    """Check that additional keywords passed to save_module_list are processed by the model"""
```

2023-08-23 13:38 UTC, gabe-l-hart commented on tests/core/modules/test_module.py
> +    dummy_block = caikit.core.load(model_path)
```suggestion
    dummy_model = caikit.core.load(model_path)
```

2023-08-23 13:38 UTC, gabe-l-hart commented on tests/core/modules/test_module.py
> +    dummy_models_with_rel_path = {"dummy_path": dummy_block}
```suggestion
    dummy_models_with_rel_path = {"dummy_path": dummy_model}
```

2023-08-23 13:38 UTC, gabe-l-hart commented on tests/core/modules/test_module.py
> +            dummy_block,
```suggestion
            dummy_model,
```

2023-08-23 14:01 UTC, gabe-l-hart approved these changes
Looks great!

2023-08-23 16:52 UTC, merged