Improve Support for Default Dataclass Fields
caikit/caikit pull request #726
Opened 2024-05-29 14:10 UTC by HonakerM

**What this PR does / why we need it**:
This PR improves the way Caikit handles default fields in 2 main ways. The first is to always honoring dataclass default/default_factory fields while the second is improved visibility in the openapi generation. 

**Special notes for your reviewer**:
I discovered a bug in the vectors code where the vectors assumed default value would be `None` instead of the `list`  defined in the factory

**If applicable**:
- [ ] this PR contains documentation
- [ ] this PR contains unit tests
- [ ] this PR has been tested for backwards compatibility

2024-06-03 15:10 UTC, gabe-l-hart requested changes
This is some nice surgery to make the `@dataclass` behavior more canonical. Since it's deep in the guts, I've got a couple of places I'd like clarifying comments, but otherwise I think this will be a nice improvement!

2024-06-03 15:55 UTC, HonakerM commented on caikit/core/data_model/dataobject.py
> +                if defined_default == dataclasses.MISSING:
Yep! `is` is definitely semantically correct.

2024-06-03 15:56 UTC, HonakerM commented on caikit/core/data_model/dataobject.py
>              if _has_dataclass_init(cls):
Sadly not, I saw that but didn't know a good way around it. There seems to be a lot of dependencies on this implementation

2024-06-03 15:56 UTC, HonakerM commented on caikit/runtime/http_server/pydantic_wrapper.py
> +        if isinstance(dm_field_default, Callable):
Yep! I'll add it

2024-06-03 16:14 UTC, HonakerM commented on tests/interfaces/common/test_vectors.py
> +    assert not new_dm_from_init.data.values
> Ah, interesting. Is the default now an empty list?

Yep! It actually aligns with the[ default defined  in the class.](https://github.com/caikit/caikit/blob/00c792a4fceb5cb02dd5f761186a8ea3289c74f5/caikit/interfaces/common/data_model/vectors.py#L41)

2024-06-03 16:30 UTC, HonakerM commented on caikit/core/data_model/dataobject.py
> +                        continue
Good call! Just reworked it

2024-06-07 17:31 UTC, gabe-l-hart approved these changes
This looks great, thanks @HonakerM!

2024-06-07 17:31 UTC, gabe-l-hart commented on caikit/core/data_model/dataobject.py
> +                        if isinstance(defined_default, Callable):
Nice!

2024-06-07 17:31 UTC, merged